modLoader="javafml"
loaderVersion="[34,)"
license="GNU General Public License 3.0"

[[mods]]
modId="vehicle"
version="0.45.0"
displayName="MrCrayfish's Vehicle Mod"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/vehicle/update.json"
displayURL="https://mrcrayfish.com/mods?id=vehicle"
logoFile="vehicle_mod.png"
credits="Phylogeny https://github.com/Phylogeny"
authors="MrCrayfish"
description="A mod that adds vehicles into Minecraft!"

[[dependencies.vehicle]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vehicle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vehicle]]
    modId="obfuscate"
    mandatory=true
    versionRange="[0.4.0,)"
    ordering="AFTER"
    side="BOTH"